### ISSUE TITLE
[BUG] Character Bugged After 0.9.5.5 Update

### ISSUE THREAD

**Issue by DogBeatr** [valheimPlus/ValheimPlus#361]
Windows Client
- **Valheim Game Version:** 0.147.3
- **V+ Mod Version:** Hotfix 0.9.5.5

**Describe the bug**

Running the game on a server through G-Portal.  After the V+ hotfix update 0.9.5.5 was released I downloaded the file from G-Portal and installed the mod as per usual.  When I loaded the game my character was there at the character select screen but had no armor on.  Launched into the server and when I loaded in my character was stuck in first person, on a bed, and the tutorial bird crow was on top of me.  Couldn't move, no items in inventory, no skills etc.  Tried reinstalling the game and the same issue.  

**Screenshots** (Copy the link and paste, not sure how to add a proper link)

[https://imgur.com/gallery/JRVmtQW](url)

**Additional context**

No other mods installed.

**Comment by eksime** [comment]
I also have just gotten this bug, it's wiped myself and 2 friends characters :(

The following is spewed in the log 
```
[Info   : Unity Log] 03/14/2021 00:45:53: Destroying old local player

[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
ValheimPlus.GameClasses.AreaRepair+Player_SetGuardianPower_Patch.Postfix (Player& __instance) (at <6131bb854b7143b1a19a263ac8807dbb>:0)
(wrapper dynamic-method) Player.DMD<Player::SetGuardianPower>(Player,string)
Player.Load (ZPackage pkg) (at <f48d6a22696245bf8d820aad6afa4fdb>:0)
PlayerProfile.LoadPlayerData (Player player) (at <f48d6a22696245bf8d820aad6afa4fdb>:0)
Game.SpawnPlayer (UnityEngine.Vector3 spawnPoint) (at <f48d6a22696245bf8d820aad6afa4fdb>:0)
Game.UpdateRespawn (System.Single dt) (at <f48d6a22696245bf8d820aad6afa4fdb>:0)
Game.FixedUpdate () (at <f48d6a22696245bf8d820aad6afa4fdb>:0)
```

While your character is reset to an "empty" character and vibrates at the spawn:

https://user-images.githubusercontent.com/5482039/111053993-ae3ea500-8460-11eb-9849-f2cb902f55bc.mp4

**Comment by GroovyChris** [comment]
Currently experiencing the same issue.
I also tried to make a new character and join the server, and the issue persisted.

**Comment by Mixone-FinallyHere** [comment]
Hey!

We have patched it just now, we will push it asap ^^

**Comment by DogBeatr** [comment]
Wow you guys are fast.  That's awesome!

**Comment by nxPublic** [comment]
We uploaded a new version for 0.9.5.5, redownload. It should be fixed now. Sorry about the inconveniences.

**Comment by eksime** [comment]
Hey, sorry is the version labelled at 0.9.5.5 (https://github.com/valheimPlus/ValheimPlus/releases/latest) on GitHub the correct version to download? - it's still showing as being updated ~2 hours ago

**Comment by DogBeatr** [comment]
I can load in now and play, however now my character looks different and is basically a new character with no skills etc.  Same character name though.

**Comment by Tukarius** [comment]
Game will load in and character name is the same, but no inventory or skills that I had before.
